### ISSUE TITLE
Data Structures

### ISSUE THREAD

**Issue by ruifcardoso** [swathysubhash/docprint#1]
Hi,

This library is exactly what I'm looking for, but unfortunately it isn't working very well with data structures.

If I use, for example, the [Data Structures example](https://raw.githubusercontent.com/apiaryio/api-blueprint/master/examples/10.%20Data%20Structures.md) from apiblueprint, it doesn't work. Ignoring the missing HOST problem, which is easily fixed by adding `HOST:` in after `FORMAT:`, it fails to load the datastructure because the element has no content. Here is the output I found adding a `console.log(result)` at `parse.js:23`:

```
Result object parsing: { element: 'dataStructure', content: [ { element: 'Coupon' } ] }
```
Because the meta is empty, it fails and crashes.

Thanks

**Comment by swathysubhash** [comment]
Fixed
